services:
  tennis-stroke-analyzer:
    build:
      context: .
      dockerfile: Dockerfile
    image: tennis-stroke-analyzer:${BUILD_DATE}
    container_name: tennis-stroke-analyzer
    volumes:
      - ./src/tennis_analyzer:/usr/app/src/tennis_analyzer
      - ./data:/usr/app/src/data
      - ./output:/usr/app/src/output
    restart: no